# Use an official Node.js runtime as the base image
FROM node:20

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of the application files to the container
COPY . .

# Build the React app for production
# RUN npm run build

EXPOSE 3000

RUN chmod +x setup.sh && ./setup.sh

# Specify the command to run when the container starts
CMD ["npm", "start"]
